.Dd $\&Mdocdate$
.Dt SNAPDL 1
.Sh NAME
.Nm snapdl
.Nd download snapshots of OpenBSD -current
.Sh SYNOPSIS
.Nm snapdl
.Sh DESCRIPTION
.Nm
helps you to find mirrors where snapshots of -current are synchronised
with the main mirror
.Pa http://ftp.OpenBSD.org
and to download the sets from the fastest one. It is interactive, the
questions (get a new mirror list, which countries, path de download
sets, which plateform, which sets, which mirror) try to be as
straightforward as those from the OpenBSD install and upgrade scripts.
.Sh FILES
.Bl -tag -width "~/.snapdl/mirrors.dat"
.It ~/.snapdl/mirrors.dat
mirrors.dat
.Nm
download from
.Pa http://www.openbsd.org/build/mirrors.dat
.It ~/.snapdl/countries
file containing one country name per line that will be automatically
checked by
.Nm
.El
.Sh SEE ALSO
.Pa http://www.openbsd.org/faq/current.html
.Sh AUTHOR
.An Nicolas P. M. Legrand Aq nlegrand@ethelred.fr .

