.Dd $Mdocdate: April 25 2010 $
.Dt SNAPDL 1
.Sh NAME
.Nm snapdl
.Nd download snapshots of OpenBSD -current
.Sh SYNOPSIS
.Nm snapdl
.Sh DESCRIPTION
.Nm
helps you to find mirrors with snapshots of -current synced with the
main mirror
.Pa http://ftp.OpenBSD.org
and to download the sets from the fastest one. It is interactive, the
questions (path de download sets, which plateform, which sets, which
mirror) try to be as straightforward as those from the OpenBSD install
and upgrade scripts.
.Sh SEE ALSO
.Pa http://www.openbsd.org/faq/current.html
.Sh AUTHOR
.An Nicolas P. M. Legrand Aq nlegrand@ethelred.fr .

